### ISSUE TITLE
Cant retrieve credentials from config files

### ISSUE THREAD

**Issue by taliptako** [beyondcode/laravel-credentials#3]
I'm setting credentials and i can retrieve them from php artisan tinker but when i try to retrieve from config file i'm getting this error

> In Container.php line 767:
> Class encrypter does not exist  
                                  
Edit: its probably because laravel preparing config files before the encrypter class loads

**Comment by mpociot** [comment]
I just published a new version 1.1.0 that allows the usage of the helper function inside your configuration files.
It works by returning a prefixed string and then replace all prefixed configuration strings once the service provider gets booted.

This also works in combination with configuration caching. So if you cache your configuration files, this will not happen and does not introduce any performance issues.

**Comment by rmoraes-tray** [comment]
@mpociot the same problem happens when is used fallback in the helper from the config file, ex: `credentials('my-nonexistent-key', 'fallback-value')` i'm getting this value:

> ___credentials_my-nonexistent-key

Instead of my `fallback-value`

https://github.com/beyondcode/laravel-credentials/blob/master/src/helpers.php#L23

And debugging `$e`

![image](https://user-images.githubusercontent.com/4967225/59944696-ccb66e80-943b-11e9-9185-bf45c0364f6b.png)
